/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuenta_por_cobrar;

import FuncionesGenerales.Dao;
import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import com.mycompany.menube_app.formularios.FrmLogin;
import com.mycompany.menube_app.formularios.FrmOutBuscarClientes;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmInOtrasCuentasPorCobrar extends javax.swing.JFrame {

    /**
     * Creates new form FrmInOtrasCuentasPorCobrar
     */
    Funciones funciones = new Funciones();
    WebServices webServices = new WebServices();
    String idcliente = "0";
    public FrmInOtrasCuentasPorCobrar() {
        initComponents();
        funciones.addNumberFieldFloat(txtMonto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscarClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConcepto = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroExterno = new javax.swing.JTextField();
        txtFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRecibos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(64, 149, 191));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuentas Por Cobrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Nombre :");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        btnBuscarClientes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnBuscarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_search_173095.png"))); // NOI18N
        btnBuscarClientes.setText("Buscar Cliente");
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Concepto :");

        txtConcepto.setColumns(20);
        txtConcepto.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtConcepto.setLineWrap(true);
        txtConcepto.setRows(5);
        txtConcepto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtConcepto);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Monto :");

        txtMonto.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 102, 51));
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Numero Externo :");

        txtNumeroExterno.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNumeroExterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroExternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroExternoKeyReleased(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Vence :");

        btnSalvar.setBackground(new java.awt.Color(0, 204, 102));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(102, 204, 255));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRecibos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        btnRecibos.setText("Recibos");
        btnRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRecibos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumeroExterno, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarClientes))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        // TODO add your handling code here:

        FrmOutBuscarClientes frm = new FrmOutBuscarClientes((JFrame) this.getParent(), true);
        frm.setVisible(true);
        frm.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
               String id = frm.getIdcliente();
               idcliente = id;
               llenar_datos_clientes(id);
               txtMonto.requestFocus();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void txtNumeroExternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroExternoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroExternoKeyPressed

    private void txtNumeroExternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroExternoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroExternoKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        eventoSalvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        eventoNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if (funciones.mensajeConfirmacion("Desea Salir del sistema", "", JOptionPane.YES_NO_OPTION) == 1) {
            return;
        }
        String respuesta = "";
        try {
            respuesta = webServices.buscar("", "ws/logout");
            if (!respuesta.equals("")) {
            }
        } catch (Exception e) {
            System.err.println("Error en salir punto venta en el metodo logout" + e.getMessage());
        }
        dispose();
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        login.setTitle("Login de Usuario");
        login.getContentPane().setBackground(new Color(64, 149, 191));
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibosActionPerformed
        // TODO add your handling code here:
        FrmRecibos frmCuentaPorCobrar = new FrmRecibos(this,true);
        frmCuentaPorCobrar.setVisible(true);
        frmCuentaPorCobrar.getContentPane().setBackground(Color.WHITE);
      
    }//GEN-LAST:event_btnRecibosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInOtrasCuentasPorCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInOtrasCuentasPorCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInOtrasCuentasPorCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInOtrasCuentasPorCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInOtrasCuentasPorCobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRecibos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConcepto;
    private org.jdesktop.swingx.JXDatePicker txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroExterno;
    // End of variables declaration//GEN-END:variables

    public void eventoSalvar()
    {
        if (idcliente.equals("") || idcliente.equals("0")) {
            funciones.mensaje("Seleccione el cliente","Aviso",JOptionPane.WARNING_MESSAGE);
            btnBuscarClientes.requestFocus();
            return;
        }
        
        if (txtMonto.getText().equals("") || funciones.parseDouble(txtMonto.getText())== 0.00) {
            funciones.mensaje("Digite el monto, este no puede estar vacio o en cero","Aviso",JOptionPane.WARNING_MESSAGE);
            txtMonto.requestFocus();
            return;
        }
        if (txtFecha.getDate()==null) {
            funciones.mensaje("Seleccione la fecha de vencimiento","Aviso",JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocus();
            return;
        }
        String concepto="CUENTA POR PAGAR";
        if (!txtConcepto.getText().equals("")) {
            concepto = txtConcepto.getText();
        }
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String fecha_vencimiento = simpleDateFormat.format(txtFecha.getDate());
        
         String json = "{"
                    + "\"f_idcliente\":\"" + idcliente + "\","
                    + "\"f_concepto\":\"" + concepto + "\","
                    + "\"f_numero_externo\":\"" + txtNumeroExterno.getText() + "\","
                    + "\"f_total\":\"" + funciones.parseDouble(txtMonto.getText()) + "\","
                    + "\"f_fecha_vencimiento\":\"" + fecha_vencimiento + "\"}";
         
     

            Map map;
            String respuesta = "";
            try {
                respuesta = webServices.buscar("\"f_cuenta_por_cobrar\":" + json, "cxc/set_salvar_otra_cuenta_por_cobrar");
                if (!respuesta.equals("")) {
                    map = funciones.JsonToMap(respuesta);

                    String[] data = map.get("f_data").toString().split("-");
                    if (data[0].equals("true")) {
                        funciones.mensaje("Datos Guardados Correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        eventoImprimir(data[1], 1);
                        btnNuevo.doClick();
                    }
                }
            } catch (Exception e) {
                System.err.println("Punto Salvar Cuentas Por Cobrar  ==>eventoSalvar ==> " + e.getMessage());

            }
        
    }
    public void  eventoNuevo(){
        idcliente = "0";
        txtNombre.setText("");
        txtConcepto.setText("");
        txtMonto.setText("");
        txtNumeroExterno.setText("");
        txtFecha.setDate(null);
        btnBuscarClientes.requestFocus();
        //eventoImprimir("5", 1);
        
    }
    public void llenar_datos_clientes(String idrecord) {
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("\"f_idrecord\":\"" + idrecord + "\"", "ws/get_clientes_by_id");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));
                for (Map tupla : map1) {

                    if (!Boolean.valueOf(tupla.get("f_tiene_credito").toString())) {
                        funciones.mensaje("El cliente no posee credito con nosotros", "", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    String nombre_cliente = "";
                    nombre_cliente += tupla.get("f_nombre").toString() != null ? tupla.get("f_nombre").toString() : "";
                    nombre_cliente += tupla.get("f_apellido").toString() != null ? tupla.get("f_apellido").toString() : "";
                    txtNombre.setText(nombre_cliente);

                }
            }

        } catch (Exception ex) {
            System.err.println("FrmCerrarFactura => cargar datos cliente => " + ex.getMessage());
        }
    }
    
     public void eventoImprimir(String id, int tipo) {
        String json = "";
        try {
            String tipo_impresion = "CUENTA POR COBRAR";

            Dao dao = new Dao();
            String respuesta = "";
            respuesta = webServices.buscar("\"f_idrecord\":" + id, "cxc/get_imprimir_cuenta_cobrar");
            if (!respuesta.equals("")) {
                //papel Matricial
                if (dao.getTipo_papel().equals("1")) {

                    funciones.GenerarStringCuentaPorCobrarImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion,false);
                    funciones.GenerarStringCuentaPorCobrarImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion,true);

                }//papel termico
                else if (dao.getTipo_papel().equals("2")) {

                    //funciones.GenerarStringFacturaImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion);
                    
                     funciones.GenerarStringCuentaPorCobrarImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion,false);
                     funciones.GenerarStringCuentaPorCobrarImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion,true);
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            System.err.println("Impresion Cuenta Por Cobrar=> evento Imprimir => " + ex.getMessage());
        }

    }

}
