/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menube_app.formularios;

import FuncionesGenerales.Combo;
import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmInCerrarFactura extends javax.swing.JDialog {

    /**
     * @return the _razon_social
     */
    public String getRazon_social() {
        return _razon_social;
    }

    /**
     * @param _razon_social the _razon_social to set
     */
    public void setRazon_social(String _razon_social) {
        this._razon_social = _razon_social;
    }

    /**
     * @return the _rnc
     */
    public String getRnc() {
        return _rnc;
    }

    /**
     * @param _rnc the _rnc to set
     */
    public void setRnc(String _rnc) {
        this._rnc = _rnc;
    }

    int getTipo_ncf() {
        return tipo_ncf;
    }

    void setTipo_ncf(int tipo_ncf) {
        this.tipo_ncf = tipo_ncf;
    }
    private int tipo_ncf = 0;

    Boolean getSi_no() {
        return si_no;
    }

    void setSi_no(Boolean si_no) {
        this.si_no = si_no;
    }
    private Boolean si_no = false;

    int getTipo_tarjeta() {
        return tipo_tarjeta;
    }

    void setTipo_tarjeta(int tipo_tarjeta) {
        this.tipo_tarjeta = tipo_tarjeta;
    }
    private int tipo_tarjeta = 0;

    int getTipo_pago() {
        return tipo_pago;
    }

    void setTipo_pago(int tipo_pago) {
        this.tipo_pago = tipo_pago;
    }
    private int tipo_pago = 0;

    String getNumero_autorizacion() {
        return numero_autorizacion;
    }

    void setNumero_autorizacion(String numero_autorizacion) {
        this.numero_autorizacion = numero_autorizacion;
    }

    private String numero_autorizacion = "";

    Double getMonto_por_tarjeta() {
        return monto_por_tarjeta;
    }

    void setMonto_por_tarjeta(Double monto_por_tarjeta) {
        this.monto_por_tarjeta = monto_por_tarjeta;
    }

    private Double monto_por_tarjeta = 0.00;

    Double getPropina_dada() {
        return propina_dada;
    }

    void setPropina_dada(Double propina_dada) {
        this.propina_dada = propina_dada;
    }

    private Double propina_dada = 0.00;

    Double getDevuelta() {
        return devuelta ;
    }

    void setDevuelta(Double devuelta) {
        this.devuelta = devuelta;
    }
    private Double devuelta = 0.00;

    Double getMonto_efetivo() {
        return monto_efetivo;
    }

    void setMonto_efetivo(Double monto_efetivo) {
        this.monto_efetivo = monto_efetivo;
    }
    private Double monto_efetivo = 0.00;

    private int idcliente;
    
    private String _razon_social;
    private String _rnc;
    private Boolean _valida_rnc = false;
    private Boolean _valido_rnc = false;

    /**
     * Creates new form FrmInCerrarFactura
     */
    Funciones funciones = new Funciones();
    WebServices webServices = new WebServices();

    public FrmInCerrarFactura() {
        initComponents();
    }

    public FrmInCerrarFactura(java.awt.Frame parent, boolean modal, String monto_total) {
        super(parent, modal);
        initComponents();
        txtmontoPagar.setEditable(true);
        txtmontoPagar.setText(monto_total);
        txtmontoPagar.setEditable(false);

        funciones.addNumberFieldFloat(txtmontoPagar);
        funciones.addNumberFieldFloat(txtefectivo);
        funciones.addNumberFieldFloat(txtmontoPagar);
        funciones.addNumberFieldFloat(txtPropina);

        llenar();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnfacturar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtefectivo = new javax.swing.JTextField();
        txtcambio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbtipoTarjeta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtmontoTarjeta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtautorizacionTarjeta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPropina = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtcodigocliente = new javax.swing.JTextField();
        btnbuscarCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtnombreCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCreditoDisponible = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDirecicon = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cbNcf = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmontoPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 149, 191));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CERRAR FACTURA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnfacturar.setBackground(new java.awt.Color(64, 149, 191));
        btnfacturar.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnfacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btnfacturar.setText("Facturar");
        btnfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 0, 0));
        btnsalir.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel4.setText("Efectivo :");

        txtefectivo.setBackground(new java.awt.Color(0, 0, 0));
        txtefectivo.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        txtefectivo.setForeground(new java.awt.Color(0, 153, 51));
        txtefectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtefectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtefectivoKeyReleased(evt);
            }
        });

        txtcambio.setEditable(false);
        txtcambio.setBackground(new java.awt.Color(255, 255, 255));
        txtcambio.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        txtcambio.setForeground(new java.awt.Color(0, 0, 0));
        txtcambio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel14.setText("Cambio :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(txtefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Efectivo", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Tipo :");

        cbtipoTarjeta.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Monto :");

        txtmontoTarjeta.setBackground(new java.awt.Color(0, 0, 0));
        txtmontoTarjeta.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtmontoTarjeta.setForeground(new java.awt.Color(0, 102, 51));
        txtmontoTarjeta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Autorización :");

        txtautorizacionTarjeta.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtautorizacionTarjeta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Propina :");

        txtPropina.setBackground(new java.awt.Color(0, 0, 0));
        txtPropina.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtPropina.setForeground(new java.awt.Color(0, 102, 51));
        txtPropina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbtipoTarjeta, 0, 321, Short.MAX_VALUE)
                            .addComponent(txtmontoTarjeta)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPropina, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtautorizacionTarjeta))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmontoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtautorizacionTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tarjeta", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("Cliente :");

        txtcodigocliente.setEditable(false);
        txtcodigocliente.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        btnbuscarCliente.setBackground(new java.awt.Color(64, 149, 191));
        btnbuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarCliente.setText("...");
        btnbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarClienteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel11.setText("Nombre :");

        txtnombreCliente.setEditable(false);
        txtnombreCliente.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setText("Direccion :");

        txtCreditoDisponible.setEditable(false);
        txtCreditoDisponible.setBackground(new java.awt.Color(0, 0, 0));
        txtCreditoDisponible.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        txtCreditoDisponible.setForeground(new java.awt.Color(0, 153, 51));
        txtCreditoDisponible.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setText("Credito Disponible :");

        txtDirecicon.setColumns(20);
        txtDirecicon.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDirecicon.setRows(5);
        jScrollPane1.setViewportView(txtDirecicon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCreditoDisponible)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCreditoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(10, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Credito", jPanel4);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("NCF :");

        cbNcf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbNcf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNcfItemStateChanged(evt);
            }
        });
        cbNcf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNcfActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel2.setText("MONTO :");

        txtmontoPagar.setEditable(false);
        txtmontoPagar.setBackground(new java.awt.Color(0, 0, 0));
        txtmontoPagar.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        txtmontoPagar.setForeground(new java.awt.Color(0, 153, 51));
        txtmontoPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(txtmontoPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtmontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(btnfacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbNcf, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfacturar)
                    .addComponent(btnsalir))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbNcf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addContainerGap(493, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        setSi_no(false);
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarClienteActionPerformed
        // TODO add your handling code here:
        FrmOutBuscarClientes frm = new FrmOutBuscarClientes((JFrame) this.getParent(), true);
        frm.setVisible(true);
        frm.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (!frm.getIdcliente().equals("0") && !frm.getIdcliente().equals("")) {
                    llenar_datos_clientes(frm.getIdcliente());
                }

            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnbuscarClienteActionPerformed

    private void txtefectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivoKeyReleased
        // TODO add your handling code here:

        if (txtefectivo.getText().equals("")) {
            return;
        }

        txtcambio.setEditable(true);

        Double valor = funciones.parseDouble(txtmontoPagar.getText());
        Double monto_efectivo = 0.00;

        if (!txtefectivo.getText().equals("")) {
            monto_efectivo = funciones.parseDouble(txtefectivo.getText());
        }

        Double cambio = monto_efectivo - valor;
        if (cambio > 0) {

            txtcambio.setText(funciones.Round(cambio, 2));
        } else {
            txtcambio.setText(funciones.Round(0, 2));
        }

        txtcambio.setEditable(false);


    }//GEN-LAST:event_txtefectivoKeyReleased

    private void btnfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturarActionPerformed
        // TODO add your handling code here:
        setTipo_pago(jTabbedPane1.getSelectedIndex());
        setSi_no(true);
        eventoFacturar();
    }//GEN-LAST:event_btnfacturarActionPerformed

    private void cbNcfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNcfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbNcfActionPerformed

    private void cbNcfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNcfItemStateChanged
        
        if (evt.getStateChange()==1) {
               eventoValidarNcf();
        }
    }//GEN-LAST:event_cbNcfItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInCerrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInCerrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInCerrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInCerrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInCerrarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarCliente;
    private javax.swing.JButton btnfacturar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<Combo> cbNcf;
    private javax.swing.JComboBox<Combo> cbtipoTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCreditoDisponible;
    private javax.swing.JTextArea txtDirecicon;
    private javax.swing.JTextField txtPropina;
    private javax.swing.JTextField txtautorizacionTarjeta;
    private javax.swing.JTextField txtcambio;
    private javax.swing.JTextField txtcodigocliente;
    private javax.swing.JTextField txtefectivo;
    private javax.swing.JTextField txtmontoPagar;
    private javax.swing.JTextField txtmontoTarjeta;
    private javax.swing.JTextField txtnombreCliente;
    // End of variables declaration//GEN-END:variables

    public void llenar() {

        txtefectivo.requestFocus();
        jTabbedPane1.setSelectedIndex(0);
        llenar_ncf();
        llenar_tarjetas();
    }

    public void llenar_ncf() {
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("", "ws/get_comprobante_fiscales");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));
                for (Map tupla : map1) {
                    Combo combo = new Combo(tupla.get("f_idrecord").toString(), tupla.get("f_descripcion").toString());
                    cbNcf.addItem(combo);
                }
            }

        } catch (Exception ex) {
            System.err.println("FrmCerrarFactura => llenar ncf => " + ex.getMessage());
        }
        
        
        
    }

    public void llenar_tarjetas() {
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("", "ws/get_tipo_tarjetas");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));
                for (Map tupla : map1) {
                    Combo combo = new Combo(tupla.get("f_idrecord").toString(), tupla.get("f_descripcion").toString());
                    cbtipoTarjeta.addItem(combo);
                }
            }

        } catch (Exception ex) {
            System.err.println("FrmCerrarFactura => llenar tarjetas => " + ex.getMessage());
        }
    }

    public void llenar_datos_clientes(String idrecord) {
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("\"f_idrecord\":\"" + idrecord + "\"", "ws/get_clientes_by_id");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));
                for (Map tupla : map1) {
                    if (!Boolean.valueOf(tupla.get("f_tiene_credito").toString())) {
                        funciones.mensaje("El cliente no posee credito con nosotros", "", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    setIdcliente(Integer.valueOf(idrecord));
                    String nombre_cliente = "";
                    String direccion = "";
                    String limite_credito = "";
                    String codigo = "";
                    nombre_cliente += tupla.get("f_nombre").toString() != null ? tupla.get("f_nombre").toString() : "";
                    nombre_cliente += tupla.get("f_apellido").toString() != null ? tupla.get("f_apellido").toString() : "";
                    direccion = tupla.get("f_direccion").toString() != null ? tupla.get("f_direccion").toString() : "";
                    limite_credito = tupla.get("f_limite_credito").toString() != null ? tupla.get("f_limite_credito").toString() : "";
                    codigo = tupla.get("f_codigo_cliente").toString() != null ? tupla.get("f_codigo_cliente").toString() : "";

                    txtnombreCliente.setEditable(true);
                    txtcodigocliente.setEditable(true);
                    txtDirecicon.setEditable(true);
                    txtCreditoDisponible.setEditable(true);

                    txtnombreCliente.setText(nombre_cliente);
                    txtcodigocliente.setText(codigo);
                    txtDirecicon.setText(direccion);
                    txtCreditoDisponible.setText(funciones.Round(limite_credito, 2));

                    txtnombreCliente.setEditable(false);
                    txtcodigocliente.setEditable(false);
                    txtDirecicon.setEditable(false);
                    txtCreditoDisponible.setEditable(false);

                }
            }

        } catch (Exception ex) {
            System.err.println("FrmCerrarFactura => cargar datos cliente => " + ex.getMessage());
        }
    }
    
    public void eventoValidarNcf()
    {
        Map map;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("\"f_idrecord\":\"" + ((Combo)cbNcf.getSelectedItem()).getId() + "\"", "ws/get_validar_ncf");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                String [] split = map.get("f_data").toString().split("#");
                
                
                if (split[0].equals("-1")) {
                    funciones.mensaje("El comprobante seleccionado a caducado su vigencia, por favor llame a la administracion","",JOptionPane.ERROR_MESSAGE);
                    btnfacturar.setEnabled(false);
                    _valida_rnc = false;
                }else{
                    if (split[1].equals("-1")) {
                        _valida_rnc = true;
                        FrmValidarRnc frm = new FrmValidarRnc((JFrame)this.getParent(),true);
                        frm.setVisible(true);
                        frm.addWindowListener(new WindowListener() {
                            @Override
                            public void windowOpened(WindowEvent e) {
                            }

                            @Override
                            public void windowClosing(WindowEvent e) {
                            }

                            @Override
                            public void windowClosed(WindowEvent e) {
                                if (frm.getStatus().equals("ACTIVO")) {
                                    _valido_rnc = true;
                                    setRnc(frm.getRnc());
                                    setRazon_social(frm.getNombre());                                    
                                  
                                }else{
                                    _valido_rnc = false;
                                     setRnc("");
                                    setRazon_social("");
                                }
                                
                            }

                            @Override
                            public void windowIconified(WindowEvent e) {
                            }

                            @Override
                            public void windowDeiconified(WindowEvent e) {
                            }

                            @Override
                            public void windowActivated(WindowEvent e) {
                            }

                            @Override
                            public void windowDeactivated(WindowEvent e) {
                            }
                        });
                    }else{
                        _valida_rnc = false;
                    }
                     btnfacturar.setEnabled(true);
                }
            }

        } catch (Exception ex) {
            System.err.println("FrmCerrarFactura => validar rnc => " + ex.getMessage());
        }
    }

    public void eventoFacturar() {

        Double monto_cambio = 0.00;
        Double monto_efectivo = 0.00;
        Double monto_tarjeta = 0.00;
        Double monto_promina = 0.00;

        if (((Combo) cbNcf.getSelectedItem()).getId().equals("0")) {
            funciones.mensaje("Seleccione el NCF", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        setTipo_ncf(Integer.valueOf(((Combo) cbNcf.getSelectedItem()).getId()));
        if (_valida_rnc==true) {
            if (_valido_rnc==false) {
                funciones.mensaje("Por Favor valide un RNC,se eligio el comprobante "+((Combo)cbNcf.getSelectedItem()).getNombre());
                return;
            }
        }
        
        if (getTipo_pago() == 0 || getTipo_pago() == 1) {

            if (!txtefectivo.getText().equals("")) {
                monto_cambio = funciones.parseDouble(txtcambio.getText());
                monto_efectivo = funciones.parseDouble(txtefectivo.getText());
            }

            if (!txtPropina.getText().equals("")) {
                monto_promina = funciones.parseDouble(txtPropina.getText());
            }

            if (!txtmontoTarjeta.getText().equals("")) {
                monto_tarjeta = funciones.parseDouble(txtmontoTarjeta.getText());
            }

            if (monto_tarjeta > 0) {

                if (txtautorizacionTarjeta.getText().equals("")) {
                    funciones.mensaje("Digite la autorizacion ", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                } else {
                    setNumero_autorizacion(txtautorizacionTarjeta.getText());
                }

                if (((Combo) cbtipoTarjeta.getSelectedItem()).getId().equals("0")) {

                    funciones.mensaje("Seleccione el tipo de tarjeta ", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                } else {
                    setTipo_tarjeta(Integer.valueOf(((Combo) cbtipoTarjeta.getSelectedItem()).getId()));
                }
            }

            Double monto_cobrar = funciones.parseDouble(txtmontoPagar.getText());
            Double total = monto_efectivo + monto_tarjeta;

            if (monto_cobrar > total) {
                funciones.mensaje("El monto efectivo o tarjeta no es suficiente para cerrar la factura ", "", JOptionPane.WARNING_MESSAGE);
                return;
            }

            setMonto_por_tarjeta(monto_tarjeta);
            setPropina_dada(monto_promina);
            setDevuelta(monto_cambio);
            setMonto_efetivo(monto_efectivo);
            
            
            
            dispose();

        }


        if (getTipo_pago() == 2) {
            if (getIdcliente() == 0 || (getIdcliente() + "").equals("")) {
                funciones.mensaje("Seleccione el cliente", "", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                Double monto_pagar = funciones.parseDouble(txtmontoPagar.getText());
                Double credito_disponible = funciones.parseDouble(txtCreditoDisponible.getText());

                if (monto_pagar > credito_disponible) {
                    funciones.mensaje("EL monto de la factura es mayor que el credito del cliente", "", JOptionPane.WARNING_MESSAGE);
                    return;
                } else {
                    dispose();
                }
            }
        }
    }

    /**
     * @return the idcliente
     */
    public int getIdcliente() {
        return idcliente;
    }

    /**
     * @param idcliente the idcliente to set
     */
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

}
