/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menube_app.formularios;

import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Usuario
 */
public class FrmInCuadre extends javax.swing.JDialog {

    private String idusuario = "";

    public String getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    WebServices webServices = new WebServices();
    Funciones funciones = new Funciones();

    /**
     * Creates new form FrmInCuadre
     */
    public FrmInCuadre() {
        initComponents();
    }

    public FrmInCuadre(java.awt.Frame parent, boolean modal, String idusuario, String nombre_usuario) {
        super(parent, modal);
        initComponents();

        tabla.removeColumn(tabla.getColumnModel().getColumn(3));
        tabla.removeColumn(tabla.getColumnModel().getColumn(0));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        tabla.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);

        tabla.getTableHeader().setFont(new Font("Tahoma", 1, 16));
        tabla.setRowHeight(40);
        tabla.setFont(new Font("Tahoma", 1, 16));

        llenar_billetes();
        lblusuario.setText(nombre_usuario);
        setIdusuario(idusuario);
        get_total_usuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tanota = new javax.swing.JTextArea();
        lblusuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txttotalBilletes = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCuadrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 149, 191));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuadre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nota :");

        tanota.setColumns(20);
        tanota.setRows(5);
        jScrollPane1.setViewportView(tanota);

        lblusuario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 0));
        lblusuario.setText("Usuario :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total :");

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(0, 0, 0));
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txttotal.setForeground(new java.awt.Color(0, 153, 51));
        txttotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tabla.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BILLETE", "CANTIDAD", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Total :");

        txttotalBilletes.setEditable(false);
        txttotalBilletes.setBackground(new java.awt.Color(0, 0, 0));
        txttotalBilletes.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txttotalBilletes.setForeground(new java.awt.Color(0, 153, 51));
        txttotalBilletes.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnNuevo.setBackground(new java.awt.Color(64, 149, 191));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCuadrar.setBackground(new java.awt.Color(64, 149, 191));
        btnCuadrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCuadrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCuadrar.setText("Cuadrar");
        btnCuadrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadrarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttotalBilletes))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCuadrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblusuario))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txttotalBilletes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuadrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        eventoNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCuadrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadrarActionPerformed
        // TODO add your handling code here:
        eventoCuadrar();
    }//GEN-LAST:event_btnCuadrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == 10) {
            calcular();
        }
    }//GEN-LAST:event_tablaKeyReleased

    private void tablaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE) || (vChar == '.'))) {
            evt.consume();
        }
    }//GEN-LAST:event_tablaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInCuadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInCuadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInCuadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInCuadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInCuadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuadrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea tanota;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalBilletes;
    // End of variables declaration//GEN-END:variables

    public void get_total_usuario() {

        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("'f_idrecord':'" + getIdusuario() + "'", "get_total_cajero");
            if (!respuesta.equals("")) {

                map = funciones.JsonToMap(respuesta);
                txttotal.setText(funciones.Round(map.get("f_data"), 2));
            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    public void llenar_billetes() {

        funciones.eliminar_tabla(tabla);

        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("", "get_lista_tipo_billete");
            if (!respuesta.equals("")) {

                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));

                for (Map tupla : map1) {

                    DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                    model.addRow(new Object[]{
                        tupla.get("f_idrecord").toString(),
                        tupla.get("f_descripcion").toString(),
                        "",
                        tupla.get("f_valor").toString(),});
                }

            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    public void calcular() {
        Double total = 0.00;
        for (int i = 0; i < tabla.getRowCount(); i++) {

            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            Double cantidad = funciones.parseDouble(model.getValueAt(i, 2).toString());
            Double valor = funciones.parseDouble(model.getValueAt(i, 3).toString());

            total += cantidad * valor;
        }
        txttotalBilletes.setText(funciones.Round(total.toString(), 2));

    }
    public void eventoCuadrar()
    {
        
        Double cuentas_abiertas = 0.00;
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("'f_idrecord':'" + getIdusuario() + "'", "get_cuentas_abiertas_cajeros");
            if (!respuesta.equals("")) {

                map = funciones.JsonToMap(respuesta);
               cuentas_abiertas = funciones.parseDouble(map.get("f_data").toString());
            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        
        
        System.err.println(" la cuentas abiertas son = " + cuentas_abiertas);
        if (cuentas_abiertas > 0) {
            funciones.mensaje("Existen cuentas que no an sido cerradas","",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if (getIdusuario().equals("") || getIdusuario().equals("0")) {
            funciones.mensaje("Debe Seleccionar un usuario","",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if (funciones.parseDouble(txttotalBilletes.getText()) <=0 || txttotalBilletes.getText().equals("")) {
            funciones.mensaje("No se puede registrar el Pull Out faltan los datos correspondiente","",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String json_detalle = CrearJsonDetalles();
        System.err.println(json_detalle);
        Double total_registrado = funciones.parseDouble(txttotalBilletes.getText());
        Double total_del_dia = funciones.parseDouble(txttotal.getText());
        
        
        String json = "{"
                + "'f_idusuario':'" + getIdusuario() + "',"
                + "'f_total_del_dia':'" + total_del_dia + "',"
                + "'f_total_registrado':'" + total_registrado + "',"
                + "'f_detalle':" + json_detalle + ","
                + "'f_nota':'" + tanota.getText()+ "'}";
        
       
        
       // return;
        try {
            respuesta = webServices.buscar("'f_cuadre':" + json, "set_salvar_cuadre");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);

                if (map.get("f_data").toString().equals("true")) {
                    funciones.mensaje("Cuadre Generado correctamente", "", JOptionPane.INFORMATION_MESSAGE);
                    //btnNueva_factura.doClick();
                    //btnNuevo.doClick();
                    btnSalir.doClick();
                }
            }
        } catch (Exception e) {
            System.err.println("Punto venta ==>eventoSalvar ==> " + e.getMessage());

        }
        
    }
    
    
    public String CrearJsonDetalles() {
        String detalle = "";
        String aux_detalle = "";

        for (int i = 0; i < tabla.getRowCount(); i++) {
            DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
            Double valor = funciones.parseDouble(modelo.getValueAt(i, 3).toString());
            Double cantidad_en_tabla =0.00;
            
            if(!modelo.getValueAt(i, 2).toString().equals("")){
                cantidad_en_tabla = funciones.parseDouble(modelo.getValueAt(i, 2).toString());
            }
            String billete= modelo.getValueAt(i, 1).toString();
            String idrecord = modelo.getValueAt(i, 0).toString();

            aux_detalle = "{"
                    + "'f_idrecord':'" + idrecord + "',"
                    + "'f_billete':'" + billete + "',"
                    + "'f_cantidad':'" + cantidad_en_tabla + "',"
                    + "'f_valor':'" + valor + "'"
                    + "},";

            detalle += aux_detalle;
        }

        detalle = "[" + detalle + "]";
        detalle = detalle.replace(",]", "]");

        return detalle;
    }
    
    public void eventoNuevo(){
        txttotal.setEditable(true);
        txttotal.setText("");
        txttotal.setEditable(false);
        
        txttotalBilletes.setEditable(true);
        txttotalBilletes.setText("");
        txttotalBilletes.setEditable(false);
        
        tanota.setText("");
        llenar_billetes();
        get_total_usuario();
        
    }
}
