/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menube_app.formularios;

import com.mycompany.menube_app.formularios.delivery.FrmDelivery;
import FuncionesGenerales.Dao;
import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import FuncionesGenerales.datos_preferencias;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mycompany.menube_app.FrmOutOpciones;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmLogin extends javax.swing.JFrame {

    public int opcion_edicion = 0;
    /**
     * Creates new form FrmLogin
     */
    Funciones funciones = new Funciones();
    Dao dao;
    WebServices webServices = new WebServices();

    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        empresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        borrar_todo = new javax.swing.JButton();
        contrasena = new javax.swing.JPasswordField();
        configuracion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        entrar.setBackground(new java.awt.Color(64, 149, 191));
        entrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        usuario.setBackground(new java.awt.Color(64, 149, 191));
        usuario.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });

        empresa.setBackground(new java.awt.Color(64, 149, 191));
        empresa.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        empresa.setForeground(new java.awt.Color(255, 255, 255));
        empresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        empresa.setEnabled(false);
        empresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empresaFocusGained(evt);
            }
        });
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empresaKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Empresa :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Usuario :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Contraseña :");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        uno.setBackground(new java.awt.Color(64, 149, 191));
        uno.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("1");
        jPanel4.add(uno);

        dos.setBackground(new java.awt.Color(64, 149, 191));
        dos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("2");
        jPanel4.add(dos);

        tres.setBackground(new java.awt.Color(64, 149, 191));
        tres.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setText("3");
        jPanel4.add(tres);

        cuatro.setBackground(new java.awt.Color(64, 149, 191));
        cuatro.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setText("4");
        jPanel4.add(cuatro);

        cinco.setBackground(new java.awt.Color(64, 149, 191));
        cinco.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setText("5");
        jPanel4.add(cinco);

        seis.setBackground(new java.awt.Color(64, 149, 191));
        seis.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setText("6");
        jPanel4.add(seis);

        siete.setBackground(new java.awt.Color(64, 149, 191));
        siete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        siete.setForeground(new java.awt.Color(255, 255, 255));
        siete.setText("7");
        jPanel4.add(siete);

        ocho.setBackground(new java.awt.Color(64, 149, 191));
        ocho.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ocho.setForeground(new java.awt.Color(255, 255, 255));
        ocho.setText("8");
        jPanel4.add(ocho);

        nueve.setBackground(new java.awt.Color(64, 149, 191));
        nueve.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nueve.setForeground(new java.awt.Color(255, 255, 255));
        nueve.setText("9");
        jPanel4.add(nueve);

        borrar.setBackground(new java.awt.Color(64, 149, 191));
        borrar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("<-");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel4.add(borrar);

        cero.setBackground(new java.awt.Color(64, 149, 191));
        cero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cero.setForeground(new java.awt.Color(255, 255, 255));
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel4.add(cero);

        borrar_todo.setBackground(new java.awt.Color(64, 149, 191));
        borrar_todo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        borrar_todo.setForeground(new java.awt.Color(255, 255, 255));
        borrar_todo.setText("C");
        borrar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_todoActionPerformed(evt);
            }
        });
        jPanel4.add(borrar_todo);

        contrasena.setBackground(new java.awt.Color(64, 149, 191));
        contrasena.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        contrasena.setForeground(new java.awt.Color(255, 255, 255));
        contrasena.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasenaFocusGained(evt);
            }
        });
        contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contrasenaKeyPressed(evt);
            }
        });

        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        empresa.getAccessibleContext().setAccessibleName("");
        empresa.getAccessibleContext().setAccessibleDescription("");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setText("..");
        jPanel3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:

            //ImageIcon imageIcon = new ImageIcon(file.getPath());
            ImageIcon imageIcon = new ImageIcon(this.getClass().getResource("/menube.png"));

            Image image = imageIcon.getImage(); // transform it
            Image newimg = image.getScaledInstance(400, 100, java.awt.Image.SCALE_DEFAULT);
            imageIcon = new ImageIcon(newimg);
            logo.setIcon(imageIcon);
            logo.setText("");

            imageIcon = new ImageIcon(this.getClass().getResource("/confi.png"));
            image = imageIcon.getImage(); // transform it
            newimg = image.getScaledInstance(50, 50, java.awt.Image.SCALE_DEFAULT);
            imageIcon = new ImageIcon(newimg);
            configuracion.setIcon(imageIcon);
            configuracion.setText("");

            addKeyPressBotones(uno);
            addKeyPressBotones(dos);
            addKeyPressBotones(tres);
            addKeyPressBotones(cuatro);
            addKeyPressBotones(cinco);
            addKeyPressBotones(seis);
            addKeyPressBotones(siete);
            addKeyPressBotones(ocho);
            addKeyPressBotones(nueve);
            addKeyPressBotones(cero);
            dao = new Dao();
            WebServices.url = dao.getUrl();
            WebServices.url_rnc = dao.getUrl_rnc();
            empresa.setText(dao.getEmpresa());
//            usuario.setText("101");
//            contrasena.setText("101");
            if (empresa.getText().equals("")) {
                empresa.requestFocus();
            } else {
                usuario.requestFocus();
            }

            funciones.getRandomColor();

        } catch (Exception ex) {
            funciones.mensaje(ex.getMessage());
        }


    }//GEN-LAST:event_formWindowOpened

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceroActionPerformed

    private void empresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empresaFocusGained
        // TODO add your handling code here:
        opcion_edicion = 1;

    }//GEN-LAST:event_empresaFocusGained

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        // TODO add your handling code here:
        opcion_edicion = 2;
    }//GEN-LAST:event_usuarioFocusGained

    private void contrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenaFocusGained

        opcion_edicion = 3;
    }//GEN-LAST:event_contrasenaFocusGained

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:

        if (opcion_edicion == 1) {
            empresa.setText(empresa.getText().substring(0, empresa.getText().length() - 1));
        }
        if (opcion_edicion == 2) {
            usuario.setText(usuario.getText().substring(0, usuario.getText().length() - 1));
        }
        if (opcion_edicion == 3) {
            contrasena.setText(contrasena.getText().substring(0, contrasena.getText().length() - 1));
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void borrar_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_todoActionPerformed
        // TODO add your handling code here:

        if (opcion_edicion == 1) {
            empresa.setText("");
        }
        if (opcion_edicion == 2) {
            usuario.setText("");
        }
        if (opcion_edicion == 3) {
            contrasena.setText("");
        }
    }//GEN-LAST:event_borrar_todoActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        try {
            // TODO add your handling code here:
            FrmConfiguracion frm = new FrmConfiguracion(this, true);
            frm.setVisible(true);
            frm.getContentPane().setBackground(Color.WHITE);
            frm.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
                }

                @Override
                public void windowClosing(WindowEvent e) {
                }

                @Override
                public void windowClosed(WindowEvent e) {
                    try {
                        dao = new Dao();
                        WebServices.url = dao.getUrl();
                        WebServices.url_rnc = dao.getUrl_rnc();
                        empresa.setText(dao.getEmpresa());
                        usuario.requestFocus();
                    } catch (ClassNotFoundException ex) {
                    } catch (SQLException ex) {
                    }
                }

                @Override
                public void windowIconified(WindowEvent e) {
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
                }

                @Override
                public void windowActivated(WindowEvent e) {
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
                }
            });
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }


    }//GEN-LAST:event_configuracionActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed

        if (empresa.getText().trim().equals("") || !funciones.isNumber(empresa.getText())) {
            funciones.mensaje("Dijite la empresa", "", JOptionPane.ERROR_MESSAGE);
            empresa.requestFocus();
            return;
        } else if (usuario.getText().trim().equals("")) {
            funciones.mensaje("Digite el usuario", "", JOptionPane.ERROR_MESSAGE);
            usuario.requestFocus();
            return;
        } else if (contrasena.getText().trim().equals("")) {
            funciones.mensaje("Digite la contraseña", "", JOptionPane.ERROR_MESSAGE);
            contrasena.requestFocus();
            return;
        }

        InetAddress ip;
        String ip_maquina = "";
        try {
            ip = InetAddress.getLocalHost();
            ip_maquina = ip.getHostAddress();

        } catch (UnknownHostException ex) {

            System.err.println("Error obteniendo la ip en Login : " + ex.getMessage());
        }

        String json = "\"f_contrasena\":\"" + contrasena.getText()
                + "\",\"f_usuario\":\"" + usuario.getText()
                + "\",\"f_banda\":\"" + "-"
                + "\",\"f_imei\":\"" + ip_maquina
                + "\",\"f_modelo\":\"" + '-'
                + "\",\"f_fOperadora\":\"" + "-"
                + "\",\"f_tamano\":\"" + "0"
                + "\",\"f_empresa\":\"" + empresa.getText() + "\"";        // TODO add your handling code here:

        Map map;
        Map map1;
        System.err.println(dao.getUrl());
        try {
            json = webServices.buscar(json, "ws/login_punto_venta");
            if (!json.equals("")) {
                json = json.replace("\":true", "\":1");
                json = json.replace("\":false", "\":0");
                map = funciones.JsonToMap(json);
                webServices.token = map.get("f_key").toString();

                map1 = (Map) map.get("f_data");
                datos_preferencias.porciento_ley = Double.valueOf(map1.get("f_porciento_ley").toString());
                datos_preferencias.impuesto_incluido = Boolean.valueOf(map1.get("f_impuesto_incluido").toString());
                datos_preferencias.tipo_usuario_punto_venta = Integer.valueOf(map1.get("f_tipo_usuario_punto_venta").toString());
                datos_preferencias.nombre_usuario = map1.get("f_nombre").toString();
                datos_preferencias.idrecord = map1.get("f_idrecord").toString();
                datos_preferencias.solo_mesa = Boolean.valueOf(map1.get("f_solo_mesa").toString());
                datos_preferencias.area = Integer.valueOf(map1.get("f_area").toString());
                datos_preferencias.mesa = Integer.valueOf(map1.get("f_mesa").toString());

                switch (datos_preferencias.tipo_usuario_punto_venta) {
                    case 1:
                    case 2:
                        FrmPuntoVenta puntoVenta = new FrmPuntoVenta(datos_preferencias.nombre_usuario, datos_preferencias.idrecord);
                        puntoVenta.setVisible(true);
                        puntoVenta.getContentPane().setBackground(Color.WHITE);
                        break;
                    case 3:
                        FrmDelivery frmDelivery = new FrmDelivery(datos_preferencias.nombre_usuario, datos_preferencias.idrecord);
                        frmDelivery.setVisible(true);
                        frmDelivery.getContentPane().setBackground(Color.WHITE);
                        break;
                    case 4:
                        FrmOutOpciones frmOpciones = new FrmOutOpciones();
                        frmOpciones.setVisible(true);
                        frmOpciones.getContentPane().setBackground(Color.WHITE);
                        break;
                    case 5:
                        FrmOutOrdenesAbiertas frmcComandas = new FrmOutOrdenesAbiertas();
                        frmcComandas.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                         frmcComandas.setUndecorated(true);
                        frmcComandas.setVisible(true);
                        frmcComandas.getContentPane().setBackground(Color.WHITE);
                        break;
                }
                dispose();
            }

        } catch (IOException ex) {
            System.err.println("Frm Login =>  entrarActionPerformed => " + ex.getMessage());
        }
    }//GEN-LAST:event_entrarActionPerformed

    private void empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            entrar.doClick();
        }
    }//GEN-LAST:event_empresaKeyPressed

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            entrar.doClick();
        }
    }//GEN-LAST:event_usuarioKeyPressed

    private void contrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contrasenaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            entrar.doClick();
        }
    }//GEN-LAST:event_contrasenaKeyPressed

    public void addKeyPressBotones(JButton boton) {
        boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (opcion_edicion == 1) {
                    empresa.setText(empresa.getText() + boton.getText());
                }
                if (opcion_edicion == 2) {
                    usuario.setText(usuario.getText() + boton.getText());
                }
                if (opcion_edicion == 3) {
                    contrasena.setText(contrasena.getText() + boton.getText());
                }

            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton borrar_todo;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton configuracion;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.JTextField empresa;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton salir;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
