/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menube_app.formularios;

import FuncionesGenerales.Dao;
import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmOutReimprimirFacturas extends javax.swing.JDialog {

    /**
     * @return the si_no
     */
    public Boolean getSi_no() {
        return si_no;
    }

    /**
     * @param si_no the si_no to set
     */
    public void setSi_no(Boolean si_no) {
        this.si_no = si_no;
    }

    /**
     * Creates new form FrmOutBuscarProductos
     */
    Funciones funciones = new Funciones();
    private String idfactura = "";
    private Boolean si_no = false;

    WebServices webServices = new WebServices();

    public FrmOutReimprimirFacturas() {
        initComponents();
    }

    public FrmOutReimprimirFacturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtparametro = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        rdOrden = new javax.swing.JRadioButton();
        rdFacturadas = new javax.swing.JRadioButton();
        dpdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dphasta = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        tabla_datos.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "#DOCUMENTO", "CUENTA", "AREA", "MESA", "CAMARERO", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_datosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_datos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Desde :");

        txtparametro.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtparametro.setForeground(new java.awt.Color(0, 0, 0));
        txtparametro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtparametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtparametroKeyPressed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(64, 149, 191));
        btnbuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        rdOrden.setBackground(new java.awt.Color(255, 255, 255));
        grupo.add(rdOrden);
        rdOrden.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        rdOrden.setForeground(new java.awt.Color(0, 0, 0));
        rdOrden.setSelected(true);
        rdOrden.setText("Orden");
        rdOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOrdenActionPerformed(evt);
            }
        });

        rdFacturadas.setBackground(new java.awt.Color(255, 255, 255));
        grupo.add(rdFacturadas);
        rdFacturadas.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        rdFacturadas.setForeground(new java.awt.Color(0, 0, 0));
        rdFacturadas.setText("Facturadas");

        dpdesde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dpdesde.setForeground(new java.awt.Color(0, 0, 0));
        dpdesde.setDate(new Date());
        dpdesde.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Parametro :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Hasta :");

        dphasta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dphasta.setForeground(new java.awt.Color(0, 0, 0));
        dphasta.setDate(new Date());
        dphasta.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(868, 868, 868)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdOrden)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdFacturadas))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtparametro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addGap(12, 12, 12)
                                .addComponent(dpdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dphasta, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtparametro)
                                .addComponent(jLabel2))
                            .addComponent(dpdesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dphasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdOrden)
                            .addComponent(rdFacturadas)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(64, 149, 191));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Facturas Abiertas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        setIdfactura("0");
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tabla_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_datosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            DefaultTableModel modelo = ((DefaultTableModel) tabla_datos.getModel());
            setIdfactura(modelo.getValueAt(tabla_datos.getSelectedRow(), 0).toString());
            eventoImprimir(getIdfactura(), 2);
        }


    }//GEN-LAST:event_tabla_datosMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        llenar_facturas();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void rdOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOrdenActionPerformed

    private void txtparametroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparametroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btnbuscar.doClick();
        }
    }//GEN-LAST:event_txtparametroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOutReimprimirFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOutReimprimirFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOutReimprimirFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOutReimprimirFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOutReimprimirFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private org.jdesktop.swingx.JXDatePicker dpdesde;
    private org.jdesktop.swingx.JXDatePicker dphasta;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdFacturadas;
    private javax.swing.JRadioButton rdOrden;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla_datos;
    private javax.swing.JTextField txtparametro;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idfactura
     */
    public String getIdfactura() {
        return idfactura;
    }

    /**
     * @param idproducto the idfactura to set
     */
    public void setIdfactura(String id) {
        this.idfactura = id;
    }

    public void llenar_facturas() {

        funciones.eliminar_tabla(tabla_datos);

        String abierta = "true";
        String desde = "";
        String hasta = "";
        if (rdFacturadas.isSelected()) {
            abierta = "false";
        }

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");
        if (dpdesde.getDate() != null) {
            desde = simpleDateFormat.format(dpdesde.getDate());
        }

        if (dphasta.getDate() != null) {
            hasta = simpleDateFormat.format(dphasta.getDate());
        }
        Map map;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {

            // ((GridBagLayout) panel_camareros.getLayout()).
            respuesta = webServices.buscar("\"f_parametro\":\"" + txtparametro.getText() + "\",\"f_abierta\":\"" + abierta + "\",\"f_desde\":\"" + desde + "\",\"f_hasta\":\"" + hasta + "\"", "ws/get_facturas_reimprimir");
            if (!respuesta.equals("")) {

                map = funciones.JsonToMap(respuesta);
                map1 = funciones.JsonToListMap(map.get("f_data"));

                for (Map tupla : map1) {

                    DefaultTableModel model = (DefaultTableModel) tabla_datos.getModel();
                    model.addRow(new Object[]{
                        tupla.get("f_idfactura"),
                        tupla.get("f_numero").toString().toUpperCase(),//numero d ela cuenta
                        tupla.get("f_nombre_cuenta").toString().toUpperCase(),//nombre d ela cuenta
                        tupla.get("f_area").toString().toUpperCase(),//nombre area
                        tupla.get("f_mesa").toString().toUpperCase(),//nombre de la mesa
                        tupla.get("f_camarero").toString().toUpperCase(),//nombre del camarero
                        funciones.Round(funciones.parseDouble(tupla.get("f_total").toString()), 2),//importe de la orden
                    });

                }

            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }

    }

    public void eventoImprimir(String id, int tipo) {
        String json = "";
        try {
            String tipo_impresion = "FACTURA";

            if (tipo == 2) {
                tipo_impresion = "REIMPRESION FACTURA";
            }

            String abierta = "true";
            if (rdFacturadas.isSelected()) {
                abierta = "false";
            } else {
                tipo_impresion = "ORDEN";
            }

            Dao dao = new Dao();

            String respuesta = "";
            respuesta = webServices.buscar("\"f_idrecord\":" + id + ",\"f_abierta\":\"" + abierta + "\"", "ws/get_imprimir_factura_by_id");
            if (!respuesta.equals("")) {
                //papel Matricial
                if (dao.getTipo_papel().equals("1")) {
                    funciones.GenerarStringFacturaImprimirMatricial(respuesta, dao.getTipo_printer(), tipo_impresion);
                }//papel termico
                else if (dao.getTipo_papel().equals("2")) {

                    funciones.GenerarStringFacturaImprimirTermica(respuesta, dao.getTipo_printer(), tipo_impresion);
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            System.err.println(" Punto venta => imprimir factura => " + ex.getMessage());
            System.err.println( ex.getLocalizedMessage());
        }

    }

    public void llenar_tabla() {
        tabla_datos.removeColumn(tabla_datos.getColumnModel().getColumn(0));
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        tabla_datos.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tabla_datos.getTableHeader().setFont(new Font("Tahoma", 1, 16));
        tabla_datos.setRowHeight(40);
    }
}
