/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menube_app.formularios.delivery;

import FuncionesGenerales.Funciones;
import FuncionesGenerales.WebServices;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.codec.binary.Base64;

/**
 *
 * @author Usuario
 */
public class FrmOutDireccioneClientes extends javax.swing.JDialog {

    /**
     * Creates new form FrmOutDireccioneClientes
     */
    
    private Boolean si_no;

    public Boolean getSi_no() {
        return si_no;
    }

    public void setSi_no(Boolean si_no) {
        this.si_no = si_no;
    }
    Funciones funciones = new Funciones();
    WebServices webServices = new WebServices();

    private String nombre_cliente = "";
    private String direcicion = "";
    private long idcliente = 0;

    public long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }

    public String getNombre_cliente() {
        return nombre_cliente;
    }

    public void setNombre_cliente(String nombre_cliente) {
        this.nombre_cliente = nombre_cliente;
    }

    public String getDirecicion() {
        return direcicion;
    }

    public void setDirecicion(String direcicion) {
        this.direcicion = direcicion;
    }

    public FrmOutDireccioneClientes() {
        initComponents();
    }

    public FrmOutDireccioneClientes(java.awt.Frame parent, boolean modal, String telefono) {
        super(parent, modal);
        initComponents();

        lblTelefono.setText("Contacto Cliente :" + telefono);

        tabla_datos.removeColumn(tabla_datos.getColumnModel().getColumn(0));
        tabla_datos.getTableHeader().setFont(new Font("Tahoma", 1, 16));
        tabla_datos.setRowHeight(40);
        llenar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        btnAgrgarCuenta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTelefono.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblTelefono.setText("Contacto Cliente : 8296614156");

        tabla_datos.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TELEFONO", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_datosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_datos);
        if (tabla_datos.getColumnModel().getColumnCount() > 0) {
            tabla_datos.getColumnModel().getColumn(0).setResizable(false);
        }

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        btnAgrgarCuenta.setBackground(new java.awt.Color(0, 204, 204));
        btnAgrgarCuenta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAgrgarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgrgarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAgrgarCuenta.setText("Nuevo Telefono");
        btnAgrgarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrgarCuentaActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDireccion.setRows(5);
        jScrollPane2.setViewportView(txtDireccion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgrgarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrgarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgrgarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrgarCuentaActionPerformed
        // TODO add your handling code here:

        FrmNuevoTelefono frm = new FrmNuevoTelefono((JFrame) this.getParent(), true, lblTelefono.getText().replace("Contacto Cliente :", "").trim());
        frm.setVisible(true);
        frm.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                llenar();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });

    }//GEN-LAST:event_btnAgrgarCuentaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        setSi_no(false);
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tabla_datosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_datosMousePressed

        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            DefaultTableModel model = (DefaultTableModel) tabla_datos.getModel();
            setNombre_cliente(model.getValueAt(tabla_datos.getSelectedRow(), 1).toString());
            setDirecicion(model.getValueAt(tabla_datos.getSelectedRow(), 2).toString());
            setIdcliente(Long.valueOf(model.getValueAt(tabla_datos.getSelectedRow(), 0).toString()));
            setSi_no(true);
            dispose();
        }
        else if(evt.getClickCount() == 1) {
            DefaultTableModel model = (DefaultTableModel) tabla_datos.getModel();
            txtDireccion.setEditable(true);
            txtDireccion.setText(model.getValueAt(tabla_datos.getSelectedRow(), 2).toString());
            txtDireccion.setEditable(false);

        }
    }//GEN-LAST:event_tabla_datosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOutDireccioneClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOutDireccioneClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOutDireccioneClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOutDireccioneClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOutDireccioneClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrgarCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla_datos;
    private javax.swing.JTextArea txtDireccion;
    // End of variables declaration//GEN-END:variables

    public void llenar() {
        funciones.borrarTabla(tabla_datos);

        Map map;
        Map map_data;
        List<Map<String, Object>> map1;
        String respuesta = "";
        try {
            respuesta = webServices.buscar("\"f_telefono\":\"" + lblTelefono.getText().replace("Contacto Cliente :", "") + "\"", "delivery/get_direcciones_clientes");
            if (!respuesta.equals("")) {
                map = funciones.JsonToMap(respuesta);
                map_data = (Map) map.get("f_data");
                //llanamos la lista del detalle
                map1 = funciones.JsonToListMap(map_data.get("f_detalles"));

                for (Map tupla : map1) {
                    DefaultTableModel model = (DefaultTableModel) tabla_datos.getModel();
                    Object[] dato = new Object[]{
                        tupla.get("f_idrecord").toString(),
                        tupla.get("f_nombre").toString(),
                        tupla.get("f_direccion").toString(),};
                    model.addRow(dato);
                }
            }
        } catch (Exception ex) {

            System.err.println("Punto venta ==>  Cargar Factura Punto Venta " + ex.getMessage());
        }
    }
}
