#import "iCore.h"
#import "iHUD.h"
#import "iXUI.h"
#import "iTableView.h"
#import "iHttp.h"
#import "iJSON.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iSideMenu.h"
#import "iDebug2.h"
@class b4i_main;
@class b4i_login;
@class b4i_funciones;
@class b4i_categoria;
@class b4i_reportes;
@class b4i_facturacion;
@class b4i_perfil;
@class b4i_favoritos;
@class b4i_httputils2service;
@class _typeu;
@class _clvitem;
@class b4i_customlistview;
@class b4i_b4xcombobox;
@class b4i_b4xdrawer;
@class _multipartfiledata;
@class b4i_httpjob;
@interface b4i_direcciones : B4IStaticModule
{
@public B4IMap* __mapadir;
@public BOOL __actualizar;
@public int __toped;
@public int __topedlbl;
@public B4IList* __estados;
@public BOOL __actu;
@public int __update;
@public int __indexcombo;
@public BOOL __edition;
@public BOOL __reload;
@public B4IMap* __mapaedit;
@public int __topmarco;
@public int __toplbladres2;
@public int __topadres;
@public int __toplbl6;
@public int __toptxtcity;
@public int __toplbl7;
@public int __topbtnstate;
@public int __toplblzip;
@public int __toptxtzip;
@public iHUD* __hud;
@public B4IPage* __pagedirecciones;
@public B4IPanelWrapper* __panel2;
@public b4i_customlistview* __listadirecciones;
@public B4ILabelWrapper* __lbldir;
@public B4ILabelWrapper* __lblfecha;
@public B4ILabelWrapper* __lblprincipal;
@public B4IButtonWrapper* __btndireccionback;
@public B4IButtonWrapper* __btnsalvardireccion;
@public B4ISwitchWrapper* __chprincipal;
@public B4ILabelWrapper* __label3;
@public B4ILabelWrapper* __label2;
@public B4ITextViewWrapper* __txtdireccion;
@public B4IPanelWrapper* __panelencabezadodir2;
@public B4IPanelWrapper* __panel2v2;
@public B4IButtonWrapper* __adddireccion;
@public B4IButtonWrapper* __borrardireccion;
@public b4i_customlistview* __listadirecciones2;
@public B4IButtonWrapper* __btndireccionback2;
@public b4i_b4xcombobox* __btnstate;
@public B4IPanelWrapper* __panelfondodireccionesusa;
@public B4IButtonWrapper* __btnbackusa;
@public B4ITextViewWrapper* __txtaddress1;
@public B4ITextViewWrapper* __txtaddress2;
@public B4ITextFieldWrapper* __txtcity;
@public B4IButtonWrapper* __btnagregardireccionfinal;
@public B4ITextFieldWrapper* __txtzipcode;
@public B4IButtonWrapper* __btndeleteusa;
@public B4IPanelWrapper* __panelmarcodirrd;
@public B4IPanelWrapper* __panelfondodireccionesrd;
@public b4i_b4xcombobox* __btnprovinciacombo;
@public B4IButtonWrapper* __btnbackrd;
@public B4IPanelWrapper* __panelencabezadord;
@public B4ITextViewWrapper* __txtdirerd;
@public B4ITextFieldWrapper* __txtsector;
@public B4ITextFieldWrapper* __txtzipcoderd;
@public B4IButtonWrapper* __btnagregardirrd;
@public B4ISwitchWrapper* __chprincipalrd;
@public B4IPanelWrapper* __panelencabezadousa;
@public B4IButtonWrapper* __btndeleterd;
@public B4ILabelWrapper* __label5;
@public B4ILabelWrapper* __label6;
@public B4ILabelWrapper* __label7;
@public B4IPanelWrapper* __panelcombousa;
@public B4ILabelWrapper* __label8;
@public B4IPanelWrapper* __panelzipcode;
@public B4IPanelWrapper* __panelfondonombredir;
@public B4ILabelWrapper* __label16;
@public B4ITextFieldWrapper* __txtnombredireccion;
@public B4IButtonWrapper* __btnaceptarnombredir;
@public b4i_main* __main;
@public b4i_login* __login;
@public b4i_funciones* __funciones;
@public b4i_categoria* __categoria;
@public b4i_reportes* __reportes;
@public b4i_facturacion* __facturacion;
@public b4i_perfil* __perfil;
@public b4i_favoritos* __favoritos;
@public b4i_httputils2service* __httputils2service;

}- (NSString*)  _actualizardirecciones;
- (NSString*)  _adddireccion_click;
- (NSString*)  _borrardireccion_click;
- (NSString*)  _btnaceptarnombredir_click;
- (NSString*)  _btnagregardireccionfinal_click;
- (NSString*)  _btnagregardirrd_click;
- (void)  _btnbackrd_click;
- (void)  _btnbackusa_click;
- (NSString*)  _btndeleterd_click;
- (NSString*)  _btndeleteusa_click;
- (NSString*)  _btndireccionback2_click;
- (NSString*)  _btnnuevadireccion_click;
- (NSString*)  _btnprovinciacombo_selectedindexchanged:(int) _index;
- (NSString*)  _btnsalvardireccion_click;
- (NSString*)  _btnstate_selectedindexchanged:(int) _index;
- (NSString*)  _buscarestados;
- (NSString*)  _buscarprovincias;
- (NSString*)  _cargardirecciones;
- (NSString*)  _crear;
- (B4IPanelWrapper*)  _createlistitem:(NSString*) _dir :(long long) _fecha :(NSString*) _principal :(int) _width :(int) _height;
- (NSString*)  _ingresardirrd;
- (NSString*)  _ingresardirusa;
- (NSString*)  _initialize;
- (NSString*)  _jobdone:(b4i_httpjob*) _job;
- (NSString*)  _listadirecciones_itemclick:(int) _index :(NSObject*) _value;
- (NSString*)  _listadirecciones2_itemclick:(int) _index :(NSObject*) _value;
- (NSString*)  _msgdelete_click:(NSString*) _buttontext;
- (NSString*)  _msgedit_click:(NSString*) _buttontext;
- (NSString*)  _nombredireccion;
- (NSString*)  _process_globals;
@property (nonatomic)B4IMap* _mapadir;
@property (nonatomic)BOOL _actualizar;
@property (nonatomic)int _toped;
@property (nonatomic)int _topedlbl;
@property (nonatomic)B4IList* _estados;
@property (nonatomic)BOOL _actu;
@property (nonatomic)int _update;
@property (nonatomic)int _indexcombo;
@property (nonatomic)BOOL _edition;
@property (nonatomic)BOOL _reload;
@property (nonatomic)B4IMap* _mapaedit;
@property (nonatomic)int _topmarco;
@property (nonatomic)int _toplbladres2;
@property (nonatomic)int _topadres;
@property (nonatomic)int _toplbl6;
@property (nonatomic)int _toptxtcity;
@property (nonatomic)int _toplbl7;
@property (nonatomic)int _topbtnstate;
@property (nonatomic)int _toplblzip;
@property (nonatomic)int _toptxtzip;
@property (nonatomic)iHUD* _hud;
@property (nonatomic)B4IPage* _pagedirecciones;
@property (nonatomic)B4IPanelWrapper* _panel2;
@property (nonatomic)b4i_customlistview* _listadirecciones;
@property (nonatomic)B4ILabelWrapper* _lbldir;
@property (nonatomic)B4ILabelWrapper* _lblfecha;
@property (nonatomic)B4ILabelWrapper* _lblprincipal;
@property (nonatomic)B4IButtonWrapper* _btndireccionback;
@property (nonatomic)B4IButtonWrapper* _btnsalvardireccion;
@property (nonatomic)B4ISwitchWrapper* _chprincipal;
@property (nonatomic)B4ILabelWrapper* _label3;
@property (nonatomic)B4ILabelWrapper* _label2;
@property (nonatomic)B4ITextViewWrapper* _txtdireccion;
@property (nonatomic)B4IPanelWrapper* _panelencabezadodir2;
@property (nonatomic)B4IPanelWrapper* _panel2v2;
@property (nonatomic)B4IButtonWrapper* _adddireccion;
@property (nonatomic)B4IButtonWrapper* _borrardireccion;
@property (nonatomic)b4i_customlistview* _listadirecciones2;
@property (nonatomic)B4IButtonWrapper* _btndireccionback2;
@property (nonatomic)b4i_b4xcombobox* _btnstate;
@property (nonatomic)B4IPanelWrapper* _panelfondodireccionesusa;
@property (nonatomic)B4IButtonWrapper* _btnbackusa;
@property (nonatomic)B4ITextViewWrapper* _txtaddress1;
@property (nonatomic)B4ITextViewWrapper* _txtaddress2;
@property (nonatomic)B4ITextFieldWrapper* _txtcity;
@property (nonatomic)B4IButtonWrapper* _btnagregardireccionfinal;
@property (nonatomic)B4ITextFieldWrapper* _txtzipcode;
@property (nonatomic)B4IButtonWrapper* _btndeleteusa;
@property (nonatomic)B4IPanelWrapper* _panelmarcodirrd;
@property (nonatomic)B4IPanelWrapper* _panelfondodireccionesrd;
@property (nonatomic)b4i_b4xcombobox* _btnprovinciacombo;
@property (nonatomic)B4IButtonWrapper* _btnbackrd;
@property (nonatomic)B4IPanelWrapper* _panelencabezadord;
@property (nonatomic)B4ITextViewWrapper* _txtdirerd;
@property (nonatomic)B4ITextFieldWrapper* _txtsector;
@property (nonatomic)B4ITextFieldWrapper* _txtzipcoderd;
@property (nonatomic)B4IButtonWrapper* _btnagregardirrd;
@property (nonatomic)B4ISwitchWrapper* _chprincipalrd;
@property (nonatomic)B4IPanelWrapper* _panelencabezadousa;
@property (nonatomic)B4IButtonWrapper* _btndeleterd;
@property (nonatomic)B4ILabelWrapper* _label5;
@property (nonatomic)B4ILabelWrapper* _label6;
@property (nonatomic)B4ILabelWrapper* _label7;
@property (nonatomic)B4IPanelWrapper* _panelcombousa;
@property (nonatomic)B4ILabelWrapper* _label8;
@property (nonatomic)B4IPanelWrapper* _panelzipcode;
@property (nonatomic)B4IPanelWrapper* _panelfondonombredir;
@property (nonatomic)B4ILabelWrapper* _label16;
@property (nonatomic)B4ITextFieldWrapper* _txtnombredireccion;
@property (nonatomic)B4IButtonWrapper* _btnaceptarnombredir;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_login* _login;
@property (nonatomic)b4i_funciones* _funciones;
@property (nonatomic)b4i_categoria* _categoria;
@property (nonatomic)b4i_reportes* _reportes;
@property (nonatomic)b4i_facturacion* _facturacion;
@property (nonatomic)b4i_perfil* _perfil;
@property (nonatomic)b4i_favoritos* _favoritos;
@property (nonatomic)b4i_httputils2service* _httputils2service;
- (NSString*)  _txtdireccion_beginedit;
- (NSString*)  _txtdireccion_endedit;
- (NSString*)  _txtdireccion_textchanged:(NSString*) _oldtext :(NSString*) _newtext;
- (NSString*)  _txtzipcode_beginedit;
- (NSString*)  _txtzipcode_endedit;
- (NSString*)  _txtzipcoderd_beginedit;
- (NSString*)  _txtzipcoderd_endedit;
@end
