#import "iCore.h"
#import "iHUD.h"
#import "iXUI.h"
#import "iTableView.h"
#import "iHttp.h"
#import "iJSON.h"
#import "iStringUtils.h"
#import "iSQL.h"
#import "iPhone.h"
#import "iSideMenu.h"
#import "iDebug2.h"
@class b4i_login;
@class b4i_funciones;
@class b4i_categoria;
@class b4i_reportes;
@class b4i_facturacion;
@class b4i_direcciones;
@class b4i_perfil;
@class b4i_favoritos;
@class b4i_httputils2service;
@class _typeu;
@class _clvitem;
@class b4i_customlistview;
@class b4i_b4xcombobox;
@class b4i_b4xdrawer;
@class _multipartfiledata;
@class b4i_httpjob;
@interface b4i_main : B4IStaticModule
{
@public B4IApplicationWrapper* __app;
@public B4INavigationControllerWrapper* __navcontrol;
@public B4IPage* __page1;
@public B4IPage* __pagedetalle;
@public B4IPage* __pageaboutus;
@public NSString* __tokenpublico;
@public NSString* __token;
@public BOOL __isloged;
@public B4IList* __listafavoritos;
@public B4IMap* __mapempresainfo;
@public NSString* __url;
@public int __idempresa;
@public NSString* __jobmsj;
@public NSString* __jobmsjtitle;
@public BOOL __impuestoincluido;
@public int __cantidadproduto;
@public B4IMap* __mapadetalle;
@public B4ISQL* __sql;
@public NSString* __imei;
@public NSString* __operadora;
@public BOOL __cargaragain;
@public BOOL __reload;
@public _typeu* __usersdata;
@public BOOL __isusa;
@public B4IMap* __mapadetalleimagen;
@public b4i_b4xdrawer* __drawer;
@public b4i_customlistview* __listslide;
@public B4IButtonWrapper* __btnprincipalback;
@public B4IButtonWrapper* __btnbuscarproducto;
@public B4IButtonWrapper* __btniniciarsecion;
@public B4IButtonWrapper* __btnorden;
@public B4IPanelWrapper* __panelfooterv2;
@public B4IPanelWrapper* __paneltitulo;
@public B4ILabelWrapper* __lblcantidadproductos;
@public B4IButtonWrapper* __btnmasvendido;
@public B4IPanelWrapper* __panelslide;
@public iHUD* __hud;
@public iHUD* __hud2;
@public B4IPanelWrapper* __panel1;
@public B4ITextFieldWrapper* __txtbuscarproducto;
@public B4IButtonWrapper* __btnproductobuscarmodal;
@public B4IPanelWrapper* __panelproductosmodalview;
@public B4IButtonWrapper* __btnproductovolver;
@public B4IPanelWrapper* __panelmodalproducto;
@public B4IScrollView* __viewcategoria;
@public B4IScrollView* __hscroll;
@public B4IPanelWrapper* __paneluser;
@public B4IImageViewWrapper* __imageuser;
@public B4ISideMenuController* __smc;
@public B4IPanelWrapper* __panel2;
@public B4IPanelWrapper* __panel3;
@public B4IPanelWrapper* __panel4;
@public B4IPanelWrapper* __panel5;
@public B4IPanelWrapper* __panel6;
@public B4IPanelWrapper* __panel7;
@public B4IPanelWrapper* __panelfondodetalles;
@public B4IImageViewWrapper* __imageviewdetalles;
@public B4ILabelWrapper* __lblprecioencabezado;
@public B4ILabelWrapper* __lblnombeencabezado;
@public B4IImageViewWrapper* __imgdetallefav;
@public B4ILabelWrapper* __lblprecio;
@public B4ILabelWrapper* __lblcantidad;
@public B4IButtonWrapper* __btnbackdetalles;
@public B4IButtonWrapper* __btnagregarcarritodetalle;
@public B4IButtonWrapper* __btnless;
@public B4IButtonWrapper* __btnmore;
@public B4IPanelWrapper* __panelimagendetalles;
@public B4IPanelWrapper* __panellblcantidad;
@public B4IPanelWrapper* __panelencabezadodetalles;
@public B4IButtonWrapper* __btnbackaboutus;
@public BOOL __buscarfavoritosvar;
@public B4IPanelWrapper* __panelcategoria;
@public B4IStepperWrapper* __steppercantidad;
@public B4ILabelWrapper* __lblnombreuser;
@public B4ILabelWrapper* __lblemailuser;
@public b4i_customlistview* __listabusquedapro;
@public B4IImageViewWrapper* __imgcat;
@public B4ILabelWrapper* __lblnomcat;
@public B4ILabelWrapper* __lblcantcat;
@public b4i_login* __login;
@public b4i_funciones* __funciones;
@public b4i_categoria* __categoria;
@public b4i_reportes* __reportes;
@public b4i_facturacion* __facturacion;
@public b4i_direcciones* __direcciones;
@public b4i_perfil* __perfil;
@public b4i_favoritos* __favoritos;
@public b4i_httputils2service* __httputils2service;

}- (NSString*)  _actualizar;
- (NSString*)  _actualizarcantidad;
- (NSString*)  _application_background;
- (NSString*)  _application_start:(B4INavigationControllerWrapper*) _nav;
- (NSString*)  _btnaddproducto_click;
- (NSString*)  _btnagregarcarritodetalle_click;
- (NSString*)  _btnbackaboutus_click;
- (NSString*)  _btnbackdetalles_click;
- (NSString*)  _btnbuscarproducto_click;
- (NSString*)  _btniniciarsecion_click;
- (NSString*)  _btnmasvendido_click;
- (NSString*)  _btnorden_click;
- (NSString*)  _btnprincipalback_click;
- (NSString*)  _btnproductobuscarmodal_click;
- (NSString*)  _btnproductovolver_click;
- (NSString*)  _buscarfavoritos;
- (NSString*)  _cargarallproductos;
- (NSString*)  _cargardatos;
- (NSString*)  _cargarmasvendido;
- (B4IPanelWrapper*)  _crearpanel;
- (B4IPanelWrapper*)  _createlistitem:(NSString*) _nombre :(NSString*) _cantidad :(B4IBitmap*) _img1 :(int) _width :(int) _height;
- (B4IPanelWrapper*)  _createpanelproducto:(B4IMap*) _map;
- (B4IPanelWrapper*)  _createpanelproductoscroll:(B4IMap*) _mapapanel1 :(B4IBitmap*) _imagen;
- (NSString*)  _imgdetallefav_click;
- (NSString*)  _imgfav_click;
- (NSString*)  _initialize;
- (void)  _jobdone:(b4i_httpjob*) _job;
- (NSString*)  _listabusquedapro_itemclick:(int) _index :(NSObject*) _value;
- (NSString*)  _listproductosmodalview_selectedchanged:(int) _sectionindex :(B4ITableCell*) _cell;
- (NSString*)  _msg1_click:(NSString*) _buttontext;
- (NSString*)  _msgaddfav_click:(NSString*) _buttontext;
- (NSString*)  _msgcerrarsesion_click:(NSString*) _buttontext;
- (NSString*)  _msgdeletefav_click:(NSString*) _buttontext;
- (NSString*)  _page1_click;
- (NSString*)  _page1_resize:(int) _width :(int) _height;
- (NSString*)  _panel1_click;
- (NSString*)  _panel2_click;
- (NSString*)  _panel3_click;
- (NSString*)  _panel4_click;
- (NSString*)  _panel5_click;
- (NSString*)  _panel6_click;
- (NSString*)  _panel7_click;
- (NSString*)  _panelfondopro_click;
- (NSString*)  _paneluser_click;
- (NSString*)  _process_globals;
@property (nonatomic)B4IApplicationWrapper* _app;
@property (nonatomic)B4INavigationControllerWrapper* _navcontrol;
@property (nonatomic)B4IPage* _page1;
@property (nonatomic)B4IPage* _pagedetalle;
@property (nonatomic)B4IPage* _pageaboutus;
@property (nonatomic)NSString* _tokenpublico;
@property (nonatomic)NSString* _token;
@property (nonatomic)BOOL _isloged;
@property (nonatomic)B4IList* _listafavoritos;
@property (nonatomic)B4IMap* _mapempresainfo;
@property (nonatomic)NSString* _url;
@property (nonatomic)int _idempresa;
@property (nonatomic)NSString* _jobmsj;
@property (nonatomic)NSString* _jobmsjtitle;
@property (nonatomic)BOOL _impuestoincluido;
@property (nonatomic)int _cantidadproduto;
@property (nonatomic)B4IMap* _mapadetalle;
@property (nonatomic)B4ISQL* _sql;
@property (nonatomic)NSString* _imei;
@property (nonatomic)NSString* _operadora;
@property (nonatomic)BOOL _cargaragain;
@property (nonatomic)BOOL _reload;
@property (nonatomic)_typeu* _usersdata;
@property (nonatomic)BOOL _isusa;
@property (nonatomic)B4IMap* _mapadetalleimagen;
@property (nonatomic)b4i_b4xdrawer* _drawer;
@property (nonatomic)b4i_customlistview* _listslide;
@property (nonatomic)B4IButtonWrapper* _btnprincipalback;
@property (nonatomic)B4IButtonWrapper* _btnbuscarproducto;
@property (nonatomic)B4IButtonWrapper* _btniniciarsecion;
@property (nonatomic)B4IButtonWrapper* _btnorden;
@property (nonatomic)B4IPanelWrapper* _panelfooterv2;
@property (nonatomic)B4IPanelWrapper* _paneltitulo;
@property (nonatomic)B4ILabelWrapper* _lblcantidadproductos;
@property (nonatomic)B4IButtonWrapper* _btnmasvendido;
@property (nonatomic)B4IPanelWrapper* _panelslide;
@property (nonatomic)iHUD* _hud;
@property (nonatomic)iHUD* _hud2;
@property (nonatomic)B4IPanelWrapper* _panel1;
@property (nonatomic)B4ITextFieldWrapper* _txtbuscarproducto;
@property (nonatomic)B4IButtonWrapper* _btnproductobuscarmodal;
@property (nonatomic)B4IPanelWrapper* _panelproductosmodalview;
@property (nonatomic)B4IButtonWrapper* _btnproductovolver;
@property (nonatomic)B4IPanelWrapper* _panelmodalproducto;
@property (nonatomic)B4IScrollView* _viewcategoria;
@property (nonatomic)B4IScrollView* _hscroll;
@property (nonatomic)B4IPanelWrapper* _paneluser;
@property (nonatomic)B4IImageViewWrapper* _imageuser;
@property (nonatomic)B4ISideMenuController* _smc;
@property (nonatomic)B4IPanelWrapper* _panel2;
@property (nonatomic)B4IPanelWrapper* _panel3;
@property (nonatomic)B4IPanelWrapper* _panel4;
@property (nonatomic)B4IPanelWrapper* _panel5;
@property (nonatomic)B4IPanelWrapper* _panel6;
@property (nonatomic)B4IPanelWrapper* _panel7;
@property (nonatomic)B4IPanelWrapper* _panelfondodetalles;
@property (nonatomic)B4IImageViewWrapper* _imageviewdetalles;
@property (nonatomic)B4ILabelWrapper* _lblprecioencabezado;
@property (nonatomic)B4ILabelWrapper* _lblnombeencabezado;
@property (nonatomic)B4IImageViewWrapper* _imgdetallefav;
@property (nonatomic)B4ILabelWrapper* _lblprecio;
@property (nonatomic)B4ILabelWrapper* _lblcantidad;
@property (nonatomic)B4IButtonWrapper* _btnbackdetalles;
@property (nonatomic)B4IButtonWrapper* _btnagregarcarritodetalle;
@property (nonatomic)B4IButtonWrapper* _btnless;
@property (nonatomic)B4IButtonWrapper* _btnmore;
@property (nonatomic)B4IPanelWrapper* _panelimagendetalles;
@property (nonatomic)B4IPanelWrapper* _panellblcantidad;
@property (nonatomic)B4IPanelWrapper* _panelencabezadodetalles;
@property (nonatomic)B4IButtonWrapper* _btnbackaboutus;
@property (nonatomic)BOOL _buscarfavoritosvar;
@property (nonatomic)B4IPanelWrapper* _panelcategoria;
@property (nonatomic)B4IStepperWrapper* _steppercantidad;
@property (nonatomic)B4ILabelWrapper* _lblnombreuser;
@property (nonatomic)B4ILabelWrapper* _lblemailuser;
@property (nonatomic)b4i_customlistview* _listabusquedapro;
@property (nonatomic)B4IImageViewWrapper* _imgcat;
@property (nonatomic)B4ILabelWrapper* _lblnomcat;
@property (nonatomic)B4ILabelWrapper* _lblcantcat;
@property (nonatomic)b4i_login* _login;
@property (nonatomic)b4i_funciones* _funciones;
@property (nonatomic)b4i_categoria* _categoria;
@property (nonatomic)b4i_reportes* _reportes;
@property (nonatomic)b4i_facturacion* _facturacion;
@property (nonatomic)b4i_direcciones* _direcciones;
@property (nonatomic)b4i_perfil* _perfil;
@property (nonatomic)b4i_favoritos* _favoritos;
@property (nonatomic)b4i_httputils2service* _httputils2service;
- (NSString*)  _salvar_detalle_temporal:(B4IMap*) _map :(int) _cantidad;
- (NSString*)  _steppercantidad_valuechanged:(double) _value;
- (NSString*)  _txtbuscarproducto_enterpressed;
@end
@interface _typeu:NSObject
{
@public BOOL _IsInitialized;
@public int _idUsuario;
@public NSString* _nombre;
@public NSString* _latitud;
@public NSString* _longitud;

}
@property (nonatomic)BOOL IsInitialized;
@property (nonatomic)int idUsuario;
@property (nonatomic)NSString* nombre;
@property (nonatomic)NSString* latitud;
@property (nonatomic)NSString* longitud;
-(void)Initialize;
@end
